
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FunctionBarDb
{

using System;
    using System.Collections.Generic;
    
public partial class artikli_inventure
{

    public int ID { get; set; }

    public double kolicina_na_zalihi { get; set; }

    public double visak_manjak { get; set; }

    public int ID_artikla { get; set; }

    public Nullable<int> ID_inventure { get; set; }



    public virtual artikl artikl { get; set; }

    public virtual inventura inventura { get; set; }

    public virtual inventura inventura1 { get; set; }

}

}
