
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FunctionBarDb
{

using System;
    using System.Collections.Generic;
    
public partial class artikl
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public artikl()
    {

        this.stavka_narudzbe = new HashSet<stavka_narudzbe>();

        this.stavka_racuna = new HashSet<stavka_racuna>();

        this.artikli_inventure = new HashSet<artikli_inventure>();

    }


    public int ID { get; set; }

    public string naziv { get; set; }

    public Nullable<double> cijena { get; set; }

    public Nullable<double> normativ { get; set; }

    public Nullable<double> kolicina_na_zalihi { get; set; }

    public Nullable<double> nabavna_cijena { get; set; }

    public int id_vrsta_artikla { get; set; }

    public int id_stopa_poreza { get; set; }

    public Nullable<bool> aktivan { get; set; }



    public virtual stopa_poreza stopa_poreza { get; set; }

    public virtual vrsta_artikla vrsta_artikla { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<stavka_narudzbe> stavka_narudzbe { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<stavka_racuna> stavka_racuna { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<artikli_inventure> artikli_inventure { get; set; }

}

}
