
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FunctionBarDb
{

using System;
    using System.Collections.Generic;
    
public partial class dobavljac
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public dobavljac()
    {

        this.narudzbenicas = new HashSet<narudzbenica>();

    }


    public int OIB { get; set; }

    public string naziv { get; set; }

    public string telefon { get; set; }

    public string adresa { get; set; }

    public string IBAN { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<narudzbenica> narudzbenicas { get; set; }

}

}
