//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionBarDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezervacija
    {
        public int ID { get; set; }
        public System.DateTime datum_zaprimanja { get; set; }
        public System.DateTime datum_rezervacije { get; set; }
        public long id_zaposlenik { get; set; }
        public int id_gost { get; set; }
        public int id_stol { get; set; }
    
        public virtual gost gost { get; set; }
        public virtual stol stol { get; set; }
        public virtual zaposlenik zaposlenik { get; set; }
    }
}
