
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FunctionBarDb
{

using System;
    using System.Collections.Generic;
    
public partial class stavka_racuna
{

    public int id_racun { get; set; }

    public int id_artikl { get; set; }

    public Nullable<int> kolicina { get; set; }



    public virtual artikl artikl { get; set; }

    public virtual racun racun { get; set; }

}

}
