//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionBarDb
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;

    public partial class zaposlenik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zaposlenik()
        {
            this.narudzbenicas = new HashSet<narudzbenica>();
            this.racuns = new HashSet<racun>();
            this.rezervacijas = new HashSet<rezervacija>();
        }
    
        public long OIB { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public Nullable<System.DateTime> datum_rodenja { get; set; }
        public string adresa { get; set; }
        public string strucna_sprema { get; set; }
        public string slika_putanja { get; set; }
        public int id_vrsta_uloge { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string putanja { get; set; }
        public Image slika2
        {
            get
            {
                if (!string.IsNullOrEmpty(slika_putanja))
                {
                    string startupPath = Environment.CurrentDirectory + "\\Resources\\" + slika_putanja;
                    Console.WriteLine(startupPath);
                    try
                    {
                        return Image.FromFile(startupPath);
                    }
                    catch
                    {

                    }
                }
                return null;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<narudzbenica> narudzbenicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<racun> racuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezervacija> rezervacijas { get; set; }
        public virtual vrsta_uloge vrsta_uloge { get; set; }
    }
}
